import Head from "next/head";
import ControlCenter from "~/components/controlCenter";
import DisplayComponent from "~/components/displayComponent";
import InitialInfo from "~/components/initialInfo";
import Navbar from "~/components/navbar";

export default function Home() {
  return (
    <>
      <Head>
        <title>Keto Playground</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex min-h-screen flex-col gap-4 bg-zinc-950">
        <Navbar />
        <section className="flex min-h-[calc(100vh-56px)] flex-col items-center gap-6">
          <InitialInfo />
          <DisplayComponent />
          {/* <ControlCenter /> */}
        </section>
      </main>
    </>
  );
}
